#ifndef GUARD_CONSTANTS_CHARACTERS_H
#define GUARD_CONSTANTS_CHARACTERS_H

enum {

    CHARACTER_NONE          = 0x00,

    // Player Characters
    CHARACTER_ALM           = 0x01,
    CHARACTER_LUKAS         = 0x02,
    CHARACTER_GRAY          = 0x03,
    CHARACTER_TOBIN         = 0x04,
    CHARACTER_KLIFF         = 0x05,
    CHARACTER_FAYE          = 0x06,
    CHARACTER_SILQUE        = 0x07,
    CHARACTER_CLAIR         = 0x08,
    CHARACTER_CLIVE         = 0x09,
    CHARACTER_FORSYTH       = 0x0A,
    CHARACTER_PYTHON        = 0x0B,
    CHARACTER_CELICA        = 0x0C,
    CHARACTER_MAE           = 0x0D,
    CHARACTER_BOEY          = 0x0E,
    CHARACTER_GENNY         = 0x0F,
    CHARACTER_SABER         = 0x10,
    CHARACTER_VALBAR        = 0x11,
    CHARACTER_LEON          = 0x12,
    CHARACTER_KAMUI         = 0x13,
    CHARACTER_LUTHIER       = 0x14,
    CHARACTER_MATHILDA      = 0x15,
    CHARACTER_DELTHEA       = 0x16,
    CHARACTER_PALLA         = 0x17,
    CHARACTER_CATRIA        = 0x18,
    CHARACTER_ATLAS         = 0x19,
    CHARACTER_JESSE         = 0x1A,
    CHARACTER_DEEN          = 0x1B,
    CHARACTER_SONYA         = 0x1C,
    CHARACTER_EST           = 0x1D,
    CHARACTER_TATIANA       = 0x1E,
    CHARACTER_ZEKE          = 0x1F,
    CHARACTER_CONRAD        = 0x20,
    CHARACTER_NOMAH         = 0x21,
    CHARACTER_MYCEN         = 0x22,
    CHARACTER_ACANTHA       = 0x23,
    CHARACTER_HYAS          = 0x24,
    CHARACTER_BERKUT_CC     = 0x25,
    CHARACTER_RINEA_CC      = 0x26,
    CHARACTER_RUDOLF_CC     = 0x27,
    CHARACTER_NUIBABA_CC    = 0x28,
    CHARACTER_EMMA_CC       = 0x29,
    CHARACTER_YUZU_CC       = 0x2A,
    CHARACTER_RANDAL_CC     = 0x2B,
    CHARACTER_SHADE_CC      = 0x2C,
    CHARACTER_FERNAND_CC    = 0x2D,

    CHARACTER_PHANTOM       = 0x3F,

    // Major Enemy Characters
    CHARACTER_JEDAH_CH4     = 0x40,
    CHARACTER_MARLA_CH4     = 0x41,
    CHARACTER_HESTIA_CH4    = 0x42,
    CHARACTER_JEDAH_FINAL   = 0x43,
    CHARACTER_MARLA_FINAL   = 0x44,
    CHARACTER_HESTIA_FINAL  = 0x45,
    CHARACTER_RUDOLF        = 0x46,
    CHARACTER_SLAYDE        = 0x47,
    CHARACTER_SLAYDE_CH4    = 0x48,
    CHARACTER_DESAIX        = 0x49,
    CHARACTER_FERNAND_1     = 0x4A,
    CHARACTER_FERNAND_2     = 0x4B,
    CHARACTER_FERNAND_3     = 0x4C,
    CHARACTER_BERKUT_1      = 0x4D,
    CHARACTER_BERKUT_2      = 0x4E,
    CHARACTER_BERKUT_3      = 0x4F,
    CHARACTER_RINEA         = 0x50,
    
    //Alm-1 Bosses
    CHARACTER_BANDIT_1      = 0x51,
    CHARACTER_BANDIT_2      = 0x52,
    CHARACTER_BRIGAND_BOSS  = 0x53,
    CHARACTER_SHIELDMERC    = 0x54,
    CHARACTER_SOLDIERBOSS_1 = 0x55,
    CHARACTER_SOLDIERBOSS_2 = 0x56,
    CHARACTER_CAVALIERBOSS  = 0x57,
    CHARACTER_ZOPYRUS       = 0x58,
    
    //Celica-2 Bosses
    CHARACTER_MONSTERBOSS   = 0x59,
    CHARACTER_PIRATEBOSS_1  = 0x5A,
    CHARACTER_PIRATEBOSS_2  = 0x5B,
    CHARACTER_BARTH         = 0x5C,
    CHARACTER_CANTORBOSS    = 0x5D,
    CHARACTER_SORCERERBOSS  = 0x5E,
    CHARACTER_JARTH         = 0x5F,
    CHARACTER_ARCANISTBOSS  = 0x60,
    
    //Alm-3 Bosses
    CHARACTER_ZAXON         = 0x61,
    CHARACTER_XYZAS         = 0x62,
    CHARACTER_LAWSON        = 0x63,
    CHARACTER_GAZELLE       = 0x64,
    CHARACTER_TATARRAH      = 0x65,
    CHARACTER_DELTHEA_BOSS  = 0x66,
    
    //Celica-3 Bosses
    CHARACTER_GARTH         = 0x67,
    CHARACTER_WOLFF         = 0x68,
    CHARACTER_SONYA_BOSS    = 0x69,
    CHARACTER_DEEN_BOSS     = 0x6A,
    CHARACTER_GRIETH        = 0x6B,
    CHARACTER_BLAKE         = 0x6C,
    CHARACTER_MIKHAIL       = 0x6D,
    
    //Act 4 Bosses
    CHARACTER_GARCIA        = 0x6E,
    CHARACTER_DOLTH         = 0x6F,
    CHARACTER_JAMIL         = 0x70,
    CHARACTER_XAIZOR        = 0x71,
    CHARACTER_NUIBABA       = 0x72,
    CHARACTER_ZEKE_BOSS     = 0x73,
    CHARACTER_JEROME        = 0x74,
    CHARACTER_MAGNUS        = 0x75,
    CHARACTER_MUELLER       = 0x76,
    
    //Act 5 Named Enemies
    CHARACTER_HADES         = 0x77,
    CHARACTER_GHARN         = 0x78,
    CHARACTER_ARGENTUM      = 0x79,
    CHARACTER_AURUM         = 0x7A,
    CHARACTER_CERBERUS      = 0x7B,
    CHARACTER_NABERIUS      = 0x7C,
    
    CHARACTER_PET_MOGALL    = 0xA9,

    CHARACTER_DUMA          = 0xBE,

    CHARACTER_WALL          = 0xFE,
    CHARACTER_SNAG          = 0xFF,

};

#endif // GUARD_CONSTANTS_CHARACTERS_H
