#ifndef GBAFE_H
#define GBAFE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "agb_sram.h"
#include "armfunc.h"
#include "battle.h"
#include "bmdebug.h"
#include "bmio.h"
#include "bmmenu.h"
#include "bso.h"
#include "chap_title.h"
#include "chap_title_pointer.h"
#include "chapter.h"
#include "chapterdata.h"
#include "convoymenu.h"
#include "cp_common.h"
#include "debug-text.h"
#include "dma.h"
#include "event.h"
#include "gold.h"
#include "icon.h"
#include "irq.h"
#include "item-use.h"
#include "item.h"
#include "m4a.h"
#include "map.h"
#include "mapselect.h"
#include "mapwork.h"
#include "mu.h"
#include "oam.h"
#include "packed_data_block.h"
#include "portrait_pointer.h"
#include "proc.h"
#include "random.h"
#include "raw_text_jp.h"
#include "sound.h"
#include "sprite-anim.h"
#include "sprite.h"
#include "statscreen.h"
#include "support.h"
#include "text.h"
#include "trap.h"
#include "uimenu.h"
#include "uiutils.h"
#include "unit.h"
#include "unit_icon_data.h"
#include "unit_icon_pointer.h"
#include "constants/items.h"
#include "constants/classes.h"
#include "constants/characters.h"
#include "constants/terrains.h"

#include "global.h"

#include "gba/gba.h"

// #include "gbafe/armfunc.h"
// #include "gbafe/random.h"
// #include "gbafe/hardware.h"
// #include "gbafe/vramtransfer.h"
// #include "gbafe/proc.h"
// #include "gbafe/text.h"
// #include "gbafe/face.h"
// #include "gbafe/ap.h"
// #include "gbafe/hiobj.h"
// #include "gbafe/compress.h"
// #include "gbafe/game.h"
// #include "gbafe/item.h"
// #include "gbafe/unit.h"
// #include "gbafe/map.h"
// #include "gbafe/menu.h"
// #include "gbafe/targetselect.h"
// #include "gbafe/standunit.h"
// #include "gbafe/mu.h"
// #include "gbafe/trap.h"
// #include "gbafe/action.h"
// #include "gbafe/chapterdata.h"
// #include "gbafe/animinterpreter.h"
// #include "gbafe/ai.h"
// #include "gbafe/sound.h"
// #include "gbafe/debugprint.h"
// #include "gbafe/other.h"
// #include "gbafe/popup.h"
// #include "gbafe/icon.h"
// #include "gbafe/sram.h"
// #include "gbafe/save.h"
// #include "gbafe/event.h"
// #include "gbafe/battle.h"
// #include "gbafe/support.h"
// #include "gbafe/wm.h"
// #include "gbafe/dialogue.h"
// #include "gbafe/drawutils.h"

#ifdef __cplusplus
} // extern "C"
#endif

#endif // GBAFE_H
